### ISSUE TITLE
release code

### ISSUE THREAD

**Issue by jiahui1688** [MasterHow/FlowLens#2]
Hi hao:
    When will you release the code? Thank you!

**Comment by MasterHow** [comment]
Thanks for your interest in our work~ See https://github.com/MasterHow/FlowLens/issues/1.

**Comment by jiahui1688** [comment]
Ok, I'm looking forward to it.

**Comment by MasterHow** [comment]
We are glad to tell you that we have release the code. If you have any questions, feel free to open a new issue. =)
